# Generated by Django 4.0.4 on 2022-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_foods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='images/'),
        ),
    ]
